#spring:
#  security:
#    user:
#      name: buzz
#      password: infinity
# export SPRING_PROFILES_ACTIVE=prod

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb

taco:
  orders:
    pageSize: 10

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN

